# Site settings
title: "Sana"
email: "questions@sanamobile.org"
description: >
  Sana platform user and technical documentation.
baseurl: ""
url: "http://sanamobile.github.io" # the base hostname & protocol for your site
# twitter_username: ""
github_username:  "sanamobile"

defaults:
  - scope:
      path: "" 
    values:
      layout: "default"

collections:
    users:
        name: User Guide
        root: /users
        permalink: /users/:path/
        output: true
    developers:
        name: "Developer Guide"
        root: /developers
        permalink: /developers/:path/
        output: true

# Build settings
markdown: kramdown
